content:
  - name: pages
    label: Pages
    type: file
    path: src/content/index.mdx
    icon: home
    fields:
      - name: title
        label: Title
        type: string
        default: Norton Studios
      - name: subtitle
        label: Subtitle
        type: string
        default: Provider of Digital Solutions for the Public Sector
      - name: body
        label: Content
        type: text

  - name: about
    label: About Us
    type: file
    path: src/content/about-us.mdx
    icon: info
    fields:
      - name: title
        label: Title
        type: string
        default: About Us
      - name: body
        label: Content
        type: text

  - name: how_we_work
    label: How We Work
    type: file
    path: src/content/how-we-work.mdx
    icon: briefcase
    fields:
      - name: title
        label: Title
        type: string
        default: How We Work
      - name: body
        label: Content
        type: text

  - name: case_studies
    label: Case Studies
    type: collection
    path: src/content/case-studies
    icon: folder
    format: yaml-frontmatter
    filename: '{primary}.mdx'
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: client
        label: Client Name
        type: string
        required: true
      - name: featured_image
        label: Featured Image
        type: image
        required: false
      - name: summary
        label: Summary
        type: text
        required: false
      - name: body
        label: Content
        type: text
        required: true
      - name: technologies
        label: Technologies
        type: text
        required: false
      - name: date
        label: Publish Date
        type: date
        required: false
    view:
      fields: [title, client, date]
      primary: title
      sort: [ date, title ]
      order: desc

  - name: team
    label: Team Members
    type: collection
    path: src/content/team
    icon: users
    format: yaml-frontmatter
    filename: '{primary}.mdx'
    fields:
      - name: title
        label: Name
        type: string
        required: true
      - name: role
        label: Role
        type: string
        required: true
      - name: image
        label: Profile Image
        type: image
        required: false
      - name: body
        label: Bio
        type: text
        required: true
      - name: linkedin
        label: LinkedIn
        type: string
        required: false
      - name: github
        label: GitHub
        type: string
        required: false
      - name: twitter
        label: Twitter
        type: string
        required: false
    view:
      fields: [title, role]
      primary: title
      sort: [ date, title ]
      order: asc

media:
  input: public/images/uploads
  output: /images/uploads

site:
  url: https://www.norton-studios.co.uk
  logo: /small-logo.svg

backend:
  name: github
  repo: jesseonslow/www.norton-studios.co.uk
  branch: master