media:
  input: public/images/uploads
  output: images/uploads
  categories: ["image"]
site:
  url: https://www.sizebyte.com
  logo: /small-logo.svg
content:
  - name: home
    label: Home
    type: file
    path: src/content/index.mdx
    fields:
      - name: heading
        label: Heading
        type: string
        default: SizeByte
      - name: subheading
        label: Subheading
        type: string
        default: Beautiful Websites Made Simple
      - name: body
        label: Content
        type: rich-text
        options:
          image:
            path: src/media/assets
            extensions: [ jpg, jpeg, png ]
  - name: about
    label: About
    type: file
    path: src/content/about-us.mdx
    fields:
      - name: title
        label: Title
        type: string
        default: About Us
      - name: body
        label: Content
        type: rich-text
        options:
          image:
            path: src/media/assets
            extensions: [ jpg, jpeg, png ]
  - name: pricing
    label: Pricing
    type: file
    path: src/content/pricing.mdx
    fields:
      - name: title
        label: Title
        type: string
        default: Pricing
      - name: body
        label: Content
        type: rich-text
  - name: faq
    label: FAQ
    type: file
    path: src/content/faq.mdx
    fields:
      - name: title
        label: Title
        type: string
        default: Frequently Asked Questions
      - name: body
        label: Content
        type: text
  - name: contact
    label: Contact
    type: file
    path: src/content/contact.mdx
    fields:
      - name: title
        label: Title
        type: string
        default: Contact Us
      - name: body
        label: Content
        type: rich-text
  - name: blog
    label: Blog
    type: collection
    path: src/content/case-studies
    format: yaml-frontmatter
    filename: '{primary}.mdx'
    fields:
      - name: published
        label: Published
        type: boolean
        required: true
      - name: featured_image
        label: Featured Image
        type: image
        required: false
      - name: title
        label: Title
        type: string
        required: false
      - name: body
        label: Content
        type: rich-text
        required: true
      - name: date
        label: Publish Date
        type: date
        required: false
    view:
      fields: [title, published, date]
      primary: title
      sort: [ date, title ]
      order: desc
backend:
  name: github
  repo: jesseonslow/www.norton-studios.co.uk
  branch: master